### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by rrhegganni** [kauegimenes/adobeanalytics#1]
![error](https://cloud.githubusercontent.com/assets/15866288/14134436/d84f8528-f674-11e5-8dda-2e9ea6c6acf4.png)

I'm using the adobe-analytics and getting the above syntax error, Can you fix the above issue? 
Because of this error my node server is terminating, can you put the code inside a try-catch block so that my server is not effected.
Thanks in advance

**Comment by kaue** [comment]
@rrhegganni Hello, i belive i fixed the issue, can you please test the version 0.0.2?

Thanks.
