### ISSUE TITLE
1.4 support?

### ISSUE THREAD

**Issue by doubletaketech** [kauegimenes/adobeanalytics#2]
Does this work with the latest Adobe Analytics REST api v1,4?

**Comment by kaue** [comment]
@doubletaketech Should work with version 1.4, please try using options.version = 1.4

https://github.com/kauegimenes/adobeanalytics/blob/master/lib/client.js#L23
https://github.com/kauegimenes/adobeanalytics/blob/master/lib/report.js#L75
